import { Person } from "./types";

/**
 * Family Tree Data - Famille Diop
 *
 * ⚠️  Ce fichier est généré automatiquement par scripts/sync-family-data.ts
 *    Dernière mise à jour: 2026-02-22
 *    Source de vérité: Supabase (qshlsdjmzpoabribaemo)
 *
 * @summary
 * - **Total**: 224 personnes
 * - **Générations**: 0 (racines) à 7
 *
 * @connections
 * Principales connexions inter-familiales:
 * - Diop ↔ Ba (Birame Medor Diop × Diarra Ba)
 * - Diop ↔ Seck (Amadou Bamba Diop × Nafissatou Seck)
 * - Seck ↔ Diagne (Magatte Diop × Diarra Diagne)
 * - Seck ↔ Diouf (Mar Seck parents: Yatma Seck × Oulimata Diouf)
 * - Diallo ↔ Ba (Bilal Diallo × Diarra Ba)
 *
 * @see scripts/sync-family-data.ts pour mettre à jour ce fichier
 */
export const familyData: Person[] = [
  // ── Génération 0 (4 personnes) ──
  {"name":"Bercy Ndack Ndir","genre":"Femme","generation":0,"parents":[],"enfants":["Gabriel Birame Medor","Bakar Waly"]},
  {"name":"Charles Medor Diop","genre":"Homme","generation":0,"parents":[],"enfants":["Gabriel Birame Medor"]},
  {"name":"Daro Wade","genre":"Femme","generation":0,"parents":[],"enfants":["Fasseck Birame Lo"]},
  {"name":"Waly Bandia Gueye","genre":"Homme","generation":0,"parents":[],"enfants":["Bakar Waly"]},

  // ── Génération 1 (3 personnes) ──
  {"name":"Bakar Waly","genre":"Homme","generation":1,"parents":["Waly Bandia Gueye","Bercy Ndack Ndir"],"enfants":[]},
  {"name":"Fasseck Birame Lo","genre":"Femme","generation":1,"parents":["Daro Wade"],"enfants":["Birame Medor Diop"]},
  {"name":"Gabriel Birame Medor","genre":"Homme","generation":1,"parents":["Charles Medor Diop","Bercy Ndack Ndir"],"enfants":["Birame Medor Diop"]},

  // ── Génération 2 (6 personnes) ──
  {"name":"Bilal Diallo","genre":"Homme","generation":2,"parents":[],"enfants":["Diarra Diallo","Iba Diallo"]},
  {"name":"Birame Medor Diop","genre":"Homme","generation":2,"parents":["Fasseck Birame Lo","Gabriel Birame Medor"],"enfants":["Gabar Diop","Fatou Diop Diarra","Katy","Magne","Dieme Medor Dagana","Amadou Diop Bercy"]},
  {"name":"Diarra Ba","genre":"Femme","generation":2,"parents":[],"enfants":["Gabar Diop","Fatou Diop Diarra","Diarra Diallo","Iba Diallo"]},
  {"name":"Mota Sarr","genre":"Femme","generation":2,"parents":[],"enfants":["Yatma Seck"]},
  {"name":"Ndiogou Seck","genre":"Homme","generation":2,"parents":[],"enfants":["Yatma Seck"]},
  {"name":"William Diouf","genre":"Homme","generation":2,"parents":[],"enfants":["Oulimata Diouf"]},

  // ── Génération 3 (10 personnes) ──
  {"name":"Amadou Diop Bercy","genre":"Homme","generation":3,"parents":["Birame Medor Diop"],"enfants":[]},
  {"name":"Betty Ba","genre":"Femme","generation":3,"parents":[],"enfants":["Alioune Badara Gabar Diop"]},
  {"name":"Diarra Diallo","genre":"Femme","generation":3,"parents":["Bilal Diallo","Diarra Ba"],"enfants":[]},
  {"name":"Dieme Medor Dagana","genre":"Homme","generation":3,"parents":["Birame Medor Diop"],"enfants":[]},
  {"name":"Fatou Diop Diarra","genre":"Femme","generation":3,"parents":["Birame Medor Diop","Diarra Ba"],"enfants":["Mame Coumba Ndiaye","Djiby Ndiaye","Soce Ndiaye","Ndeye Sylvie Sene","El Hadji Malick Ndiaye"]},
  {"name":"Gabar Diop","genre":"Homme","generation":3,"parents":["Birame Medor Diop","Diarra Ba"],"enfants":["Alioune Badara Gabar Diop","Amadou Bamba Diop","Ibrahima Gabar Diop","Doudou Yaye Katy Diop","Faty Dia Mbacke Diop"]},
  {"name":"Katy","genre":"Femme","generation":3,"parents":["Birame Medor Diop"],"enfants":[]},
  {"name":"Magne","genre":"Femme","generation":3,"parents":["Birame Medor Diop"],"enfants":[]},
  {"name":"Oulimata Diouf","genre":"Femme","generation":3,"parents":["William Diouf"],"enfants":["Mar Seck","Iba Diagne"]},
  {"name":"Yatma Seck","genre":"Homme","generation":3,"parents":["Ndiogou Seck","Mota Sarr"],"enfants":["Mar Seck"]},

  // ── Génération 4 (19 personnes) ──
  {"name":"Alioune Badara Gabar Diop","genre":"Homme","generation":4,"parents":["Gabar Diop","Betty Ba"],"enfants":["Mame Diarra Diop","Ndeye Betty Diop","Amadou Diop (Doudou)","Amadou Bamba Diop (Badara)","Ndeye Salimata Diop (Badara)","Seynabou Diop (Badara)","Lissong Diop (Badara)","Gabar Birame Medor Diop","Ibrahima Gabar Diop (Badara)","Saliou Sady Faza Diop","El Hadji Malick Diop","Yacine Diop","Mouhamadou Lamine Diop"]},
  {"name":"Amadou Bamba Diop","genre":"Homme","generation":4,"parents":["Gabar Diop"],"enfants":[]},
  {"name":"Binta Sarr","genre":"Femme","generation":4,"parents":[],"enfants":["Fatou Diallo","Moustapha Diallo","Mame Diarra Diallo (Bineta Sarr)","Souleymane Diallo"]},
  {"name":"Djiby Ndiaye","genre":"Homme","generation":4,"parents":["Fatou Diop Diarra"],"enfants":[]},
  {"name":"Doudou Yaye Katy Diop","genre":"Femme","generation":4,"parents":["Gabar Diop"],"enfants":[]},
  {"name":"El Hadji Malick Ndiaye","genre":"Homme","generation":4,"parents":["Fatou Diop Diarra"],"enfants":["Feu Papa Gabar Ndiaye","Feu Pape Charles","Djibril","Fatou Iba"]},
  {"name":"Fatou Cissé","genre":"Femme","generation":4,"parents":[],"enfants":["Amadou Diop (Doudou)","Amadou Bamba Diop (Badara)","Ndeye Salimata Diop (Badara)","Seynabou Diop (Badara)"]},
  {"name":"Fatou Gaye","genre":"Femme","generation":4,"parents":[],"enfants":["Lissong Diop (Badara)","Gabar Birame Medor Diop","Ibrahima Gabar Diop (Badara)","Saliou Sady Faza Diop","El Hadji Malick Diop","Yacine Diop","Mouhamadou Lamine Diop"]},
  {"name":"Fatou Mbaye","genre":"Femme","generation":4,"parents":[],"enfants":["Feu Papa Gabar Ndiaye","Feu Pape Charles","Djibril","Fatou Iba"]},
  {"name":"Faty Dia Mbacke Diop","genre":"Femme","generation":4,"parents":["Gabar Diop"],"enfants":[]},
  {"name":"Iba Diagne","genre":"Homme","generation":4,"parents":["Oulimata Diouf"],"enfants":["Mamadou Diagne"]},
  {"name":"Iba Diallo","genre":"Homme","generation":4,"parents":["Diarra Ba","Bilal Diallo"],"enfants":["Fatou Diallo","Moustapha Diallo","Mame Diarra Diallo (Bineta Sarr)","Souleymane Diallo"]},
  {"name":"Ibrahima Gabar Diop","genre":"Homme","generation":4,"parents":["Gabar Diop"],"enfants":["Mame Coumba Diop","Aida Gabar Diop","Aminata Diop","Soukeyna Diop","Hady Diop","Fatou Mbacke Diop"]},
  {"name":"Mame Coumba Ndiaye","genre":"Femme","generation":4,"parents":["Fatou Diop Diarra"],"enfants":[]},
  {"name":"Mar Seck","genre":"Homme","generation":4,"parents":["Yatma Seck","Oulimata Diouf"],"enfants":["Binta Yama Seck","Nafissatou Seck","Aminta Seck","Mouhamadou Moustapha Seck","Penda Ndiaye Seck","Mame Aida Seck","Pathe Seck"]},
  {"name":"Marieme Ndiaye","genre":"Femme","generation":4,"parents":["Fatou Diallo"],"enfants":["Binta Yama Seck","Nafissatou Seck","Aminta Seck","Mouhamadou Moustapha Seck","Penda Ndiaye Seck","Mame Aida Seck","Pathe Seck"]},
  {"name":"Ndeye Sylvie Sene","genre":"Femme","generation":4,"parents":["Fatou Diop Diarra"],"enfants":[]},
  {"name":"Seynabou Ndoye","genre":"Femme","generation":4,"parents":[],"enfants":["Mame Diarra Diop","Ndeye Betty Diop"]},
  {"name":"Soce Ndiaye","genre":"Homme","generation":4,"parents":["Fatou Diop Diarra"],"enfants":[]},

  // ── Génération 5 (61 personnes) ──
  {"name":"Abdoulaye Douta Seck","genre":"Homme","generation":5,"parents":[],"enfants":["Marie Louise Fatimata Douta Seck"]},
  {"name":"Aida Gabar Diop","genre":"Femme","generation":5,"parents":["Ibrahima Gabar Diop"],"enfants":[]},
  {"name":"Aida Gaye","genre":"Femme","generation":5,"parents":[],"enfants":["Mame Betty Gabar Diop","El Hadj Malick Diop (Gabar Birame)","Badara Gabar Diop (Aida)"]},
  {"name":"Aita Diagne","genre":"Femme","generation":5,"parents":[],"enfants":["Astou Diop (Doudou)","Badara Gabar Diop (Doudou)"]},
  {"name":"Amadou Bamba Diop (Badara)","genre":"Homme","generation":5,"parents":["Alioune Badara Gabar Diop","Fatou Cissé"],"enfants":["Magatte Diop","Betty Bamba Diop","Bassirou Bamba Diop","Badara Gabar Diop (Khady)","Abdoulaye Diop (Khady)","Aminata Diop (Bamba)","Mame Assane Diop","Seynabou Diop (Bamba)","Soukeyna Diop (Bamba)","Ndeye Sokhna Diop","Ndeye Maguette Diop","Pape Gabar Diop","Cheikh Diop","Fatou Cissé Diop (Bamba)","Ousmane Diop","Soda Diop","Astou Diop (Bamba)","Saliou Faza Diop","Ahmadou Diop (Bamba)","Moustapha Diop (Bamba)","Abdou Salam Diop (Bamba)"]},
  {"name":"Amadou Diop (Doudou)","genre":"Homme","generation":5,"parents":["Alioune Badara Gabar Diop","Fatou Cissé"],"enfants":["Lamine Diop","Marie Diagne Diop","Marie Madeleine Diop","Lissong Diop (Doudou)","Ndeye Khar Diop","Astou Diop (Doudou)","Badara Gabar Diop (Doudou)","Ndeye Fatou Diop (Doudou)","Ahmadou Bamba Diop"]},
  {"name":"Amadou Lamine Seck","genre":"Homme","generation":5,"parents":[],"enfants":["Al Housseynou Seck","Assietou Seck","Ndeye Maguette Seck","Sokhna Seck","Mame Fatou Seck"]},
  {"name":"Aminata Diop","genre":"Femme","generation":5,"parents":["Ibrahima Gabar Diop"],"enfants":[]},
  {"name":"Aminta Seck","genre":"Femme","generation":5,"parents":["Mar Seck","Marieme Ndiaye"],"enfants":[]},
  {"name":"Amy Colé Diallo","genre":"Femme","generation":5,"parents":[],"enfants":["Lissong Diop (Doudou)"]},
  {"name":"Binta Yama Seck","genre":"Femme","generation":5,"parents":["Mar Seck","Marieme Ndiaye"],"enfants":["Ndeye Wouly Diagne","Pape Mar Diagne","Moussa Diagne","Diarra Diagne","Yatma Diagne","Nafissatou Diagne (Binta)","Mame Aida Diagne","Idrissa Diagne","Mouhamadou Tidjane Diagne","Madjiguene Diagne","Makhtar Diagne (Binta)"]},
  {"name":"Diedhiou","genre":"Homme","generation":5,"parents":[],"enfants":["Mame Aissatou Diedhiou","Maguette Fall Diedhiou","Fatou Nene Diedhiou","Alphousseynou Diedhiou","Assane Diedhiou","Ismaila Diedhiou","Mouhameth Diedhiou"]},
  {"name":"Djibril","genre":"Homme","generation":5,"parents":["El Hadji Malick Ndiaye","Fatou Mbaye"],"enfants":[]},
  {"name":"El Hadji Malick Diop","genre":"Homme","generation":5,"parents":["Alioune Badara Gabar Diop","Fatou Gaye"],"enfants":[]},
  {"name":"Faboye Ndoumbé Cissé","genre":"Femme","generation":5,"parents":[],"enfants":["Aida Gabar Diop (Faboye)","Faboye Ndoumbé Diop"]},
  {"name":"Fatou Diallo","genre":"Femme","generation":5,"parents":["Iba Diallo","Binta Sarr"],"enfants":["Marieme Ndiaye"]},
  {"name":"Fatou Goudiaby","genre":"Femme","generation":5,"parents":[],"enfants":["Lamine Diop","Marie Diagne Diop","Marie Madeleine Diop"]},
  {"name":"Fatou Gueye","genre":"Femme","generation":5,"parents":[],"enfants":["Amadou Diop (Fatou)","Ahmadou Diop (Fatou)"]},
  {"name":"Fatou Iba","genre":"Femme","generation":5,"parents":["El Hadji Malick Ndiaye","Fatou Mbaye"],"enfants":[]},
  {"name":"Fatou Mbacke Diop","genre":"Femme","generation":5,"parents":["Ibrahima Gabar Diop"],"enfants":[]},
  {"name":"Feu Papa Gabar Ndiaye","genre":"Homme","generation":5,"parents":["El Hadji Malick Ndiaye","Fatou Mbaye"],"enfants":[]},
  {"name":"Feu Pape Charles","genre":"Homme","generation":5,"parents":["El Hadji Malick Ndiaye","Fatou Mbaye"],"enfants":[]},
  {"name":"Gabar Birame Medor Diop","genre":"Homme","generation":5,"parents":["Alioune Badara Gabar Diop","Fatou Gaye"],"enfants":["Amadou Diop (Fatou)","Ahmadou Diop (Fatou)","Mame Betty Gabar Diop","El Hadj Malick Diop (Gabar Birame)","Badara Gabar Diop (Aida)"]},
  {"name":"Hady Diop","genre":"Homme","generation":5,"parents":["Ibrahima Gabar Diop"],"enfants":[]},
  {"name":"Ibrahima Gabar Diop (Badara)","genre":"Homme","generation":5,"parents":["Alioune Badara Gabar Diop","Fatou Gaye"],"enfants":["Aida Gabar Diop (Faboye)","Faboye Ndoumbé Diop","Moustapha Gabar Diop","Marieme Fatou Diop (Katy)","Aissatou Gabar Diop"]},
  {"name":"Katy Wade","genre":"Femme","generation":5,"parents":[],"enfants":["Moustapha Gabar Diop","Marieme Fatou Diop (Katy)","Aissatou Gabar Diop"]},
  {"name":"Khady Ba","genre":"Femme","generation":5,"parents":[],"enfants":["Betty Bamba Diop","Bassirou Bamba Diop","Badara Gabar Diop (Khady)","Abdoulaye Diop (Khady)"]},
  {"name":"Laurence Ba","genre":"Femme","generation":5,"parents":[],"enfants":["Marieme Nora Seck"]},
  {"name":"Lissong Diop (Badara)","genre":"Femme","generation":5,"parents":["Alioune Badara Gabar Diop","Fatou Gaye"],"enfants":["Al Housseynou Seck","Assietou Seck","Ndeye Maguette Seck","Sokhna Seck","Mame Fatou Seck","Marie Louise Fatimata Douta Seck","Thiane Kharaachi Diagne"]},
  {"name":"Madeleine Tamba","genre":"Femme","generation":5,"parents":[],"enfants":["Seynabou Diop (Lamine)","Aida Gaye Diop","Fabaye Diop","Lissong Diop (Lamine)"]},
  {"name":"Mamadou Diagne","genre":"Homme","generation":5,"parents":["Iba Diagne"],"enfants":["Ndeye Wouly Diagne","Pape Mar Diagne","Moussa Diagne","Diarra Diagne","Yatma Diagne","Nafissatou Diagne (Binta)","Mame Aida Diagne"]},
  {"name":"Mame Aida Seck","genre":"Femme","generation":5,"parents":["Mar Seck","Marieme Ndiaye"],"enfants":[]},
  {"name":"Mame Bineta Lo","genre":"Femme","generation":5,"parents":[],"enfants":["Abibatou Diop","Marieme Fatou Diop (Bineta)","Diogomaye Diop"]},
  {"name":"Mame Coumba Diop","genre":"Femme","generation":5,"parents":["Ibrahima Gabar Diop"],"enfants":[]},
  {"name":"Mame Diarra Diallo (Bineta Sarr)","genre":"Femme","generation":5,"parents":["Iba Diallo","Binta Sarr"],"enfants":[]},
  {"name":"Mame Diarra Diop","genre":"Femme","generation":5,"parents":["Alioune Badara Gabar Diop","Seynabou Ndoye"],"enfants":["Djiby Kane","Pape Kane Modiallo","Ndeye Maguette Kane","Ndeye Ndiebou Sow","Nguissaly Fall","Badara Gabar Sow"]},
  {"name":"Mame Ngoné Dieng","genre":"Femme","generation":5,"parents":[],"enfants":["Aminata Diop (Bamba)","Mame Assane Diop","Seynabou Diop (Bamba)","Soukeyna Diop (Bamba)","Ndeye Sokhna Diop","Ndeye Maguette Diop"]},
  {"name":"Mame Penda Ndiaye","genre":"Femme","generation":5,"parents":[],"enfants":["Mouhamed Hady Diop","Mame Ndiobasse Diop","El Hadj Malick Diop (Saliou Sady)","Papa Oumar Thiam Diop"]},
  {"name":"Mansour Diop","genre":"Homme","generation":5,"parents":[],"enfants":["Cheikh Tidiane Diop","Nafissatou Diop","Ndeye Fatou Diop (Salimata)","Pape Ousmane Diop","Mame Makhtar Diop","Amadou Diop (Diobé)","Seynabou Diop (Salimata)"]},
  {"name":"Mariéme Wade","genre":"Femme","generation":5,"parents":[],"enfants":["Ndeye Khar Diop"]},
  {"name":"Mbacké Diagne","genre":"Homme","generation":5,"parents":[],"enfants":["Astou Diagne","Mbaye Diagne","Seynabou Diagne","Pape Assane Diagne","Fatou Diagne","Badara Gabar Diagne","Serigne MBacke Diagne"]},
  {"name":"Moctar Sall","genre":"Homme","generation":5,"parents":[],"enfants":["Sophie Sall","Badara Gabar Sall","Lamine Sall"]},
  {"name":"Mouhamadou Lamine Diop","genre":"Homme","generation":5,"parents":["Alioune Badara Gabar Diop","Fatou Gaye"],"enfants":["Abibatou Diop","Marieme Fatou Diop (Bineta)","Diogomaye Diop","Seynabou Diop (Lamine)","Aida Gaye Diop","Fabaye Diop","Lissong Diop (Lamine)"]},
  {"name":"Mouhamadou Moustapha Seck","genre":"Homme","generation":5,"parents":["Mar Seck","Marieme Ndiaye"],"enfants":[]},
  {"name":"Moustapha Diallo","genre":"Homme","generation":5,"parents":["Iba Diallo","Binta Sarr"],"enfants":[]},
  {"name":"Nafissatou Seck","genre":"Femme","generation":5,"parents":["Mar Seck","Marieme Ndiaye"],"enfants":["Magatte Diop","Mame Aissatou Diedhiou","Maguette Fall Diedhiou","Fatou Nene Diedhiou","Alphousseynou Diedhiou","Assane Diedhiou","Ismaila Diedhiou","Mouhameth Diedhiou"]},
  {"name":"Ndeye Betty Diop","genre":"Femme","generation":5,"parents":["Alioune Badara Gabar Diop","Seynabou Ndoye"],"enfants":["Astou Diagne","Mbaye Diagne","Seynabou Diagne","Pape Assane Diagne","Fatou Diagne","Badara Gabar Diagne","Serigne MBacke Diagne","Abdoulaye Diop (Betty)","Aminata Diop (Betty)","El Hadj Malick Diop (Ndeye Betty)"]},
  {"name":"Ndeye Coumba Seck","genre":"Femme","generation":5,"parents":[],"enfants":["Sokhna Oumou Kalsoume Seck","Pauline Seck","Aby Seck","Marieme Aicha Seck"]},
  {"name":"Ndeye Ndiaye","genre":"Femme","generation":5,"parents":[],"enfants":["Pape Gabar Diop","Cheikh Diop","Fatou Cissé Diop (Bamba)","Ousmane Diop","Soda Diop","Astou Diop (Bamba)","Saliou Faza Diop","Ahmadou Diop (Bamba)","Moustapha Diop (Bamba)","Abdou Salam Diop (Bamba)"]},
  {"name":"Ndeye Salimata Diop (Badara)","genre":"Femme","generation":5,"parents":["Alioune Badara Gabar Diop","Fatou Cissé"],"enfants":["Amadou Lamine Thiam","Cheikh Tidiane Diop","Nafissatou Diop","Ndeye Fatou Diop (Salimata)","Pape Ousmane Diop","Mame Makhtar Diop","Amadou Diop (Diobé)","Seynabou Diop (Salimata)"]},
  {"name":"Pape Diop","genre":"Homme","generation":5,"parents":[],"enfants":["Abdoulaye Diop (Betty)","Aminata Diop (Betty)","El Hadj Malick Diop (Ndeye Betty)"]},
  {"name":"Pathe Seck","genre":"Homme","generation":5,"parents":["Mar Seck","Marieme Ndiaye"],"enfants":["Makha Seck","Penda Seck","Sokhna Oumou Kalsoume Seck","Pauline Seck","Aby Seck","Marieme Aicha Seck","Marieme Nora Seck"]},
  {"name":"Penda Ndiaye Seck","genre":"Femme","generation":5,"parents":["Mar Seck","Marieme Ndiaye"],"enfants":[]},
  {"name":"Rama","genre":"Femme","generation":5,"parents":[],"enfants":["Ndeye Fatou Diop (Doudou)","Ahmadou Bamba Diop"]},
  {"name":"Saliou Sady Faza Diop","genre":"Homme","generation":5,"parents":["Alioune Badara Gabar Diop","Fatou Gaye"],"enfants":["Mouhamed Hady Diop","Mame Ndiobasse Diop","El Hadj Malick Diop (Saliou Sady)","Papa Oumar Thiam Diop"]},
  {"name":"Samba Thiam","genre":"Homme","generation":5,"parents":[],"enfants":["Amadou Lamine Thiam"]},
  {"name":"Seynabou Diop (Badara)","genre":"Femme","generation":5,"parents":["Alioune Badara Gabar Diop","Fatou Cissé"],"enfants":[]},
  {"name":"Sidy Kharaachi Diagne","genre":"Homme","generation":5,"parents":[],"enfants":["Thiane Kharaachi Diagne"]},
  {"name":"Soukeyna Diop","genre":"Femme","generation":5,"parents":["Ibrahima Gabar Diop"],"enfants":[]},
  {"name":"Souleymane Diallo","genre":"Homme","generation":5,"parents":["Iba Diallo","Binta Sarr"],"enfants":[]},
  {"name":"Yacine Diop","genre":"Femme","generation":5,"parents":["Alioune Badara Gabar Diop","Fatou Gaye"],"enfants":["Makha Seck","Penda Seck","Sophie Sall","Badara Gabar Sall","Lamine Sall"]},

  // ── Génération 6 (111 personnes) ──
  {"name":"Abdou Salam Diop (Bamba)","genre":"Homme","generation":6,"parents":["Amadou Bamba Diop (Badara)","Ndeye Ndiaye"],"enfants":[]},
  {"name":"Abdoulaye Diop (Betty)","genre":"Homme","generation":6,"parents":["Ndeye Betty Diop","Pape Diop"],"enfants":[]},
  {"name":"Abdoulaye Diop (Khady)","genre":"Homme","generation":6,"parents":["Amadou Bamba Diop (Badara)","Khady Ba"],"enfants":[]},
  {"name":"Abibatou Diop","genre":"Femme","generation":6,"parents":["Mouhamadou Lamine Diop","Mame Bineta Lo"],"enfants":[]},
  {"name":"Aby Seck","genre":"Femme","generation":6,"parents":["Pathe Seck","Ndeye Coumba Seck"],"enfants":[]},
  {"name":"Ahmadou Bamba Diop","genre":"Homme","generation":6,"parents":["Amadou Diop (Doudou)","Rama"],"enfants":[]},
  {"name":"Ahmadou Diop (Bamba)","genre":"Homme","generation":6,"parents":["Amadou Bamba Diop (Badara)","Ndeye Ndiaye"],"enfants":[]},
  {"name":"Ahmadou Diop (Fatou)","genre":"Homme","generation":6,"parents":["Gabar Birame Medor Diop","Fatou Gueye"],"enfants":[]},
  {"name":"Aida Gabar Diop (Faboye)","genre":"Femme","generation":6,"parents":["Ibrahima Gabar Diop (Badara)","Faboye Ndoumbé Cissé"],"enfants":[]},
  {"name":"Aida Gaye Diop","genre":"Femme","generation":6,"parents":["Mouhamadou Lamine Diop","Madeleine Tamba"],"enfants":[]},
  {"name":"Aissatou Gabar Diop","genre":"Femme","generation":6,"parents":["Ibrahima Gabar Diop (Badara)","Katy Wade"],"enfants":[]},
  {"name":"Al Housseynou Seck","genre":"Homme","generation":6,"parents":["Lissong Diop (Badara)","Amadou Lamine Seck"],"enfants":[]},
  {"name":"Alphousseynou Diedhiou","genre":"Homme","generation":6,"parents":["Nafissatou Seck","Diedhiou"],"enfants":[]},
  {"name":"Amadou Diop (Diobé)","genre":"Homme","generation":6,"parents":["Mansour Diop","Ndeye Salimata Diop (Badara)"],"enfants":[]},
  {"name":"Amadou Diop (Fatou)","genre":"Homme","generation":6,"parents":["Gabar Birame Medor Diop","Fatou Gueye"],"enfants":[]},
  {"name":"Amadou Lamine Thiam","genre":"Homme","generation":6,"parents":["Samba Thiam","Ndeye Salimata Diop (Badara)"],"enfants":[]},
  {"name":"Aminata Diop (Bamba)","genre":"Femme","generation":6,"parents":["Amadou Bamba Diop (Badara)","Mame Ngoné Dieng"],"enfants":[]},
  {"name":"Aminata Diop (Betty)","genre":"Femme","generation":6,"parents":["Ndeye Betty Diop","Pape Diop"],"enfants":[]},
  {"name":"Assane Diedhiou","genre":"Homme","generation":6,"parents":["Nafissatou Seck","Diedhiou"],"enfants":[]},
  {"name":"Assietou Seck","genre":"Femme","generation":6,"parents":["Lissong Diop (Badara)","Amadou Lamine Seck"],"enfants":[]},
  {"name":"Astou Diagne","genre":"Femme","generation":6,"parents":["Ndeye Betty Diop","Mbacké Diagne"],"enfants":[]},
  {"name":"Astou Diop (Bamba)","genre":"Femme","generation":6,"parents":["Amadou Bamba Diop (Badara)","Ndeye Ndiaye"],"enfants":[]},
  {"name":"Astou Diop (Doudou)","genre":"Femme","generation":6,"parents":["Amadou Diop (Doudou)","Aita Diagne"],"enfants":[]},
  {"name":"Badara Gabar Diagne","genre":"Homme","generation":6,"parents":["Ndeye Betty Diop","Mbacké Diagne"],"enfants":[]},
  {"name":"Badara Gabar Diop (Aida)","genre":"Homme","generation":6,"parents":["Gabar Birame Medor Diop","Aida Gaye"],"enfants":[]},
  {"name":"Badara Gabar Diop (Doudou)","genre":"Homme","generation":6,"parents":["Amadou Diop (Doudou)","Aita Diagne"],"enfants":["Aissatou Gabar Diop (Mbarka)","El Bachir Gabar Diop (Mbarka)","Adja Marieme Gabar Diop (Mbarka)","Djibril Mandaw Gabar Diop (Mbarka)"]},
  {"name":"Badara Gabar Diop (Khady)","genre":"Homme","generation":6,"parents":["Amadou Bamba Diop (Badara)","Khady Ba"],"enfants":[]},
  {"name":"Badara Gabar Sall","genre":"Homme","generation":6,"parents":["Yacine Diop","Moctar Sall"],"enfants":[]},
  {"name":"Badara Gabar Sow","genre":"Homme","generation":6,"parents":["Mame Diarra Diop"],"enfants":[]},
  {"name":"Bassirou Bamba Diop","genre":"Femme","generation":6,"parents":["Amadou Bamba Diop (Badara)","Khady Ba"],"enfants":[]},
  {"name":"Betty Bamba Diop","genre":"Homme","generation":6,"parents":["Amadou Bamba Diop (Badara)","Khady Ba"],"enfants":[]},
  {"name":"Cheikh Diop","genre":"Homme","generation":6,"parents":["Amadou Bamba Diop (Badara)","Ndeye Ndiaye"],"enfants":[]},
  {"name":"Cheikh Tidiane Diop","genre":"Homme","generation":6,"parents":["Mansour Diop","Ndeye Salimata Diop (Badara)"],"enfants":[]},
  {"name":"Diarra Diagne","genre":"Femme","generation":6,"parents":["Binta Yama Seck","Mamadou Diagne"],"enfants":["Ibrahima Gabar Diop (Magatte)","Fatou Cisse Diop (Magatte)","Assane Gabar Diop"]},
  {"name":"Diogomaye Diop","genre":"Homme","generation":6,"parents":["Mouhamadou Lamine Diop","Mame Bineta Lo"],"enfants":[]},
  {"name":"Djiby Kane","genre":"Homme","generation":6,"parents":["Mame Diarra Diop"],"enfants":[]},
  {"name":"El Hadj Malick Diop (Gabar Birame)","genre":"Homme","generation":6,"parents":["Gabar Birame Medor Diop","Aida Gaye"],"enfants":[]},
  {"name":"El Hadj Malick Diop (Ndeye Betty)","genre":"Homme","generation":6,"parents":["Ndeye Betty Diop","Pape Diop"],"enfants":[]},
  {"name":"El Hadj Malick Diop (Saliou Sady)","genre":"Homme","generation":6,"parents":["Saliou Sady Faza Diop","Mame Penda Ndiaye"],"enfants":[]},
  {"name":"Fabaye Diop","genre":"Homme","generation":6,"parents":["Mouhamadou Lamine Diop","Madeleine Tamba"],"enfants":[]},
  {"name":"Faboye Ndoumbé Diop","genre":"Femme","generation":6,"parents":["Ibrahima Gabar Diop (Badara)","Faboye Ndoumbé Cissé"],"enfants":[]},
  {"name":"Fatou Cissé Diop (Bamba)","genre":"Femme","generation":6,"parents":["Amadou Bamba Diop (Badara)","Ndeye Ndiaye"],"enfants":[]},
  {"name":"Fatou Diagne","genre":"Femme","generation":6,"parents":["Ndeye Betty Diop","Mbacké Diagne"],"enfants":[]},
  {"name":"Fatou Nene Diedhiou","genre":"Femme","generation":6,"parents":["Nafissatou Seck","Diedhiou"],"enfants":[]},
  {"name":"Idrissa Diagne","genre":"Homme","generation":6,"parents":["Binta Yama Seck"],"enfants":[]},
  {"name":"Ismaila Diedhiou","genre":"Homme","generation":6,"parents":["Nafissatou Seck","Diedhiou"],"enfants":[]},
  {"name":"Lamine Diop","genre":"Homme","generation":6,"parents":["Amadou Diop (Doudou)","Fatou Goudiaby"],"enfants":[]},
  {"name":"Lamine Sall","genre":"Homme","generation":6,"parents":["Yacine Diop","Moctar Sall"],"enfants":[]},
  {"name":"Lissong Diop (Doudou)","genre":"Femme","generation":6,"parents":["Amadou Diop (Doudou)","Amy Colé Diallo"],"enfants":[]},
  {"name":"Lissong Diop (Lamine)","genre":"Femme","generation":6,"parents":["Mouhamadou Lamine Diop","Madeleine Tamba"],"enfants":[]},
  {"name":"Madjiguene Diagne","genre":"Femme","generation":6,"parents":["Binta Yama Seck"],"enfants":[]},
  {"name":"Magatte Diop","genre":"Homme","generation":6,"parents":["Amadou Bamba Diop (Badara)","Nafissatou Seck"],"enfants":["Ibrahima Gabar Diop (Magatte)","Fatou Cisse Diop (Magatte)","Assane Gabar Diop","Amadou Bamba Diop (Magatte)","Lamine Gabar Diop"]},
  {"name":"Maguette Fall Diedhiou","genre":"Femme","generation":6,"parents":["Nafissatou Seck","Diedhiou"],"enfants":[]},
  {"name":"Makha Seck","genre":"Homme","generation":6,"parents":["Yacine Diop","Pathe Seck"],"enfants":[]},
  {"name":"Makhtar Diagne (Binta)","genre":"Homme","generation":6,"parents":["Binta Yama Seck"],"enfants":[]},
  {"name":"Mame Aida Diagne","genre":"Femme","generation":6,"parents":["Binta Yama Seck","Mamadou Diagne"],"enfants":[]},
  {"name":"Mame Aissatou Diedhiou","genre":"Femme","generation":6,"parents":["Nafissatou Seck","Diedhiou"],"enfants":[]},
  {"name":"Mame Assane Diop","genre":"Femme","generation":6,"parents":["Amadou Bamba Diop (Badara)","Mame Ngoné Dieng"],"enfants":[]},
  {"name":"Mame Betty Gabar Diop","genre":"Femme","generation":6,"parents":["Gabar Birame Medor Diop","Aida Gaye"],"enfants":[]},
  {"name":"Mame Fatou Seck","genre":"Femme","generation":6,"parents":["Lissong Diop (Badara)","Amadou Lamine Seck"],"enfants":[]},
  {"name":"Mame Makhtar Diop","genre":"Homme","generation":6,"parents":["Mansour Diop","Ndeye Salimata Diop (Badara)"],"enfants":[]},
  {"name":"Mame Ndiobasse Diop","genre":"Femme","generation":6,"parents":["Saliou Sady Faza Diop","Mame Penda Ndiaye"],"enfants":[]},
  {"name":"Marie Diagne Diop","genre":"Homme","generation":6,"parents":["Amadou Diop (Doudou)","Fatou Goudiaby"],"enfants":[]},
  {"name":"Marie Louise Fatimata Douta Seck","genre":"Femme","generation":6,"parents":["Lissong Diop (Badara)","Abdoulaye Douta Seck"],"enfants":[]},
  {"name":"Marie Madeleine Diop","genre":"Femme","generation":6,"parents":["Amadou Diop (Doudou)","Fatou Goudiaby"],"enfants":[]},
  {"name":"Marieme Aicha Seck","genre":"Femme","generation":6,"parents":["Pathe Seck","Ndeye Coumba Seck"],"enfants":[]},
  {"name":"Marieme Fatou Diop (Bineta)","genre":"Femme","generation":6,"parents":["Mouhamadou Lamine Diop","Mame Bineta Lo"],"enfants":[]},
  {"name":"Marieme Fatou Diop (Katy)","genre":"Femme","generation":6,"parents":["Ibrahima Gabar Diop (Badara)","Katy Wade"],"enfants":[]},
  {"name":"Marieme Nora Seck","genre":"Femme","generation":6,"parents":["Pathe Seck","Laurence Ba"],"enfants":[]},
  {"name":"Mbaye Diagne","genre":"Homme","generation":6,"parents":["Ndeye Betty Diop","Mbacké Diagne"],"enfants":[]},
  {"name":"Mouhamadou Tidjane Diagne","genre":"Homme","generation":6,"parents":["Binta Yama Seck"],"enfants":[]},
  {"name":"Mouhamed Hady Diop","genre":"Homme","generation":6,"parents":["Saliou Sady Faza Diop","Mame Penda Ndiaye"],"enfants":[]},
  {"name":"Mouhameth Diedhiou","genre":"Homme","generation":6,"parents":["Nafissatou Seck","Diedhiou"],"enfants":[]},
  {"name":"Moussa Diagne","genre":"Homme","generation":6,"parents":["Binta Yama Seck","Mamadou Diagne"],"enfants":[]},
  {"name":"Moustapha Diop (Bamba)","genre":"Homme","generation":6,"parents":["Amadou Bamba Diop (Badara)","Ndeye Ndiaye"],"enfants":[]},
  {"name":"Moustapha Gabar Diop","genre":"Homme","generation":6,"parents":["Ibrahima Gabar Diop (Badara)","Katy Wade"],"enfants":[]},
  {"name":"Nafissatou Diagne (Binta)","genre":"Femme","generation":6,"parents":["Binta Yama Seck","Mamadou Diagne"],"enfants":[]},
  {"name":"Nafissatou Diop","genre":"Femme","generation":6,"parents":["Mansour Diop","Ndeye Salimata Diop (Badara)"],"enfants":[]},
  {"name":"Ndeye Fatou Diop (Doudou)","genre":"Femme","generation":6,"parents":["Amadou Diop (Doudou)","Rama"],"enfants":[]},
  {"name":"Ndeye Fatou Diop (Salimata)","genre":"Femme","generation":6,"parents":["Mansour Diop","Ndeye Salimata Diop (Badara)"],"enfants":[]},
  {"name":"Ndeye Khar Diop","genre":"Femme","generation":6,"parents":["Amadou Diop (Doudou)","Mariéme Wade"],"enfants":[]},
  {"name":"Ndeye Maguette Diop","genre":"Femme","generation":6,"parents":["Amadou Bamba Diop (Badara)","Mame Ngoné Dieng"],"enfants":[]},
  {"name":"Ndeye Maguette Kane","genre":"Femme","generation":6,"parents":["Mame Diarra Diop"],"enfants":[]},
  {"name":"Ndeye Maguette Seck","genre":"Femme","generation":6,"parents":["Lissong Diop (Badara)","Amadou Lamine Seck"],"enfants":[]},
  {"name":"Ndeye Mbarka Diop","genre":"Femme","generation":6,"parents":[],"enfants":["Aissatou Gabar Diop (Mbarka)","Djibril Mandaw Gabar Diop (Mbarka)","El Bachir Gabar Diop (Mbarka)","Adja Marieme Gabar Diop (Mbarka)","Amadou Gabar Diop (Mbarka)"]},
  {"name":"Ndeye Ndiebou Sow","genre":"Femme","generation":6,"parents":["Mame Diarra Diop"],"enfants":[]},
  {"name":"Ndeye Sokhna Diop","genre":"Femme","generation":6,"parents":["Amadou Bamba Diop (Badara)","Mame Ngoné Dieng"],"enfants":[]},
  {"name":"Ndeye Wouly Diagne","genre":"Femme","generation":6,"parents":["Binta Yama Seck","Mamadou Diagne"],"enfants":[]},
  {"name":"Nguissaly Fall","genre":"Femme","generation":6,"parents":["Mame Diarra Diop"],"enfants":[]},
  {"name":"Ousmane Diop","genre":"Homme","generation":6,"parents":["Amadou Bamba Diop (Badara)","Ndeye Ndiaye"],"enfants":[]},
  {"name":"Papa Oumar Thiam Diop","genre":"Homme","generation":6,"parents":["Saliou Sady Faza Diop","Mame Penda Ndiaye"],"enfants":[]},
  {"name":"Pape Assane Diagne","genre":"Homme","generation":6,"parents":["Ndeye Betty Diop","Mbacké Diagne"],"enfants":[]},
  {"name":"Pape Gabar Diop","genre":"Homme","generation":6,"parents":["Amadou Bamba Diop (Badara)","Ndeye Ndiaye"],"enfants":[]},
  {"name":"Pape Kane Modiallo","genre":"Homme","generation":6,"parents":["Mame Diarra Diop"],"enfants":[]},
  {"name":"Pape Mar Diagne","genre":"Homme","generation":6,"parents":["Binta Yama Seck","Mamadou Diagne"],"enfants":[]},
  {"name":"Pape Ousmane Diop","genre":"Homme","generation":6,"parents":["Mansour Diop","Ndeye Salimata Diop (Badara)"],"enfants":[]},
  {"name":"Pauline Seck","genre":"Femme","generation":6,"parents":["Pathe Seck","Ndeye Coumba Seck"],"enfants":[]},
  {"name":"Penda Seck","genre":"Femme","generation":6,"parents":["Yacine Diop","Pathe Seck"],"enfants":[]},
  {"name":"Saliou Faza Diop","genre":"Homme","generation":6,"parents":["Amadou Bamba Diop (Badara)","Ndeye Ndiaye"],"enfants":[]},
  {"name":"Serigne MBacke Diagne","genre":"Homme","generation":6,"parents":["Ndeye Betty Diop","Mbacké Diagne"],"enfants":[]},
  {"name":"Seynabou Diagne","genre":"Femme","generation":6,"parents":["Ndeye Betty Diop","Mbacké Diagne"],"enfants":[]},
  {"name":"Seynabou Diop (Bamba)","genre":"Femme","generation":6,"parents":["Amadou Bamba Diop (Badara)","Mame Ngoné Dieng"],"enfants":[]},
  {"name":"Seynabou Diop (Lamine)","genre":"Femme","generation":6,"parents":["Mouhamadou Lamine Diop","Madeleine Tamba"],"enfants":[]},
  {"name":"Seynabou Diop (Salimata)","genre":"Femme","generation":6,"parents":["Mansour Diop","Ndeye Salimata Diop (Badara)"],"enfants":[]},
  {"name":"Soda Diop","genre":"Femme","generation":6,"parents":["Amadou Bamba Diop (Badara)","Ndeye Ndiaye"],"enfants":[]},
  {"name":"Sokhna Oumou Kalsoume Seck","genre":"Femme","generation":6,"parents":["Pathe Seck","Ndeye Coumba Seck"],"enfants":[]},
  {"name":"Sokhna Seck","genre":"Femme","generation":6,"parents":["Lissong Diop (Badara)","Amadou Lamine Seck"],"enfants":[]},
  {"name":"Sophie Sall","genre":"Femme","generation":6,"parents":["Yacine Diop","Moctar Sall"],"enfants":[]},
  {"name":"Soukeyna Diop (Bamba)","genre":"Femme","generation":6,"parents":["Amadou Bamba Diop (Badara)","Mame Ngoné Dieng"],"enfants":[]},
  {"name":"Thiane Kharaachi Diagne","genre":"Femme","generation":6,"parents":["Lissong Diop (Badara)","Sidy Kharaachi Diagne"],"enfants":[]},
  {"name":"Yatma Diagne","genre":"Homme","generation":6,"parents":["Binta Yama Seck","Mamadou Diagne"],"enfants":[]},

  // ── Génération 7 (10 personnes) ──
  {"name":"Adja Marieme Gabar Diop (Mbarka)","genre":"Femme","generation":7,"parents":["Badara Gabar Diop (Doudou)","Ndeye Mbarka Diop"],"enfants":[]},
  {"name":"Aissatou Gabar Diop (Mbarka)","genre":"Femme","generation":7,"parents":["Badara Gabar Diop (Doudou)","Ndeye Mbarka Diop"],"enfants":[]},
  {"name":"Amadou Bamba Diop (Magatte)","genre":"Homme","generation":7,"parents":["Magatte Diop"],"enfants":[]},
  {"name":"Amadou Gabar Diop (Mbarka)","genre":"Homme","generation":7,"parents":["Ndeye Mbarka Diop"],"enfants":[]},
  {"name":"Assane Gabar Diop","genre":"Homme","generation":7,"parents":["Diarra Diagne","Magatte Diop"],"enfants":[]},
  {"name":"Djibril Mandaw Gabar Diop (Mbarka)","genre":"Homme","generation":7,"parents":["Ndeye Mbarka Diop","Badara Gabar Diop (Doudou)"],"enfants":[]},
  {"name":"El Bachir Gabar Diop (Mbarka)","genre":"Homme","generation":7,"parents":["Badara Gabar Diop (Doudou)","Ndeye Mbarka Diop"],"enfants":[]},
  {"name":"Fatou Cisse Diop (Magatte)","genre":"Femme","generation":7,"parents":["Diarra Diagne","Magatte Diop"],"enfants":[]},
  {"name":"Ibrahima Gabar Diop (Magatte)","genre":"Homme","generation":7,"parents":["Diarra Diagne","Magatte Diop"],"enfants":[]},
  {"name":"Lamine Gabar Diop","genre":"Homme","generation":7,"parents":["Magatte Diop"],"enfants":[]},
];
